version: "3.8"

services:
  database:
    image: postgres:18
    container_name: profinder-db
    restart: unless-stopped
    ports:
      - "3001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 54321
      POSTGRES_DB: profinder
    volumes:
      - profinder-data:/var/lib/postgresql

volumes:
  profinder-data:
    driver: local
